ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

alias desk="~/Desktop"
alias pw="ruby ~/randompass.rb"
alias db="~/Dropbox"
alias doit="git rev-parse --abbrev-ref HEAD | xargs git pull --rebase origin  && git rev-parse --abbrev-ref HEAD | xargs git push origin "
alias alpha="ssh servers | grep -A2 app_alpha"
alias prod="ssh servers | grep -A2 app_production"
alias 1kstaging="ssh app_onekreate_staging@i.chef.realtimeprocess.net"
alias 1kalpha="ssh app_onekreate_alpha@i.chef.realtimeprocess.net"
alias 1kqa="ssh app_onekreate_qa@i.chef.realtimeprocess.net"

alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"

unsetopt correct
unsetopt correct_all

plugins=(git osx)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:/usr/local/sbin:$PATH:/Users/dseravalli/ksc/bin:/Users/dseravalli/bin

### realtime completion - begin. generated by omelette ###
if type compdef &>/dev/null; then
  _realtime_complette() {
    compadd -- `realtime --compzsh --compgen "${CURRENT}" "${words[CURRENT-1]}" "${BUFFER}"`
  }
  compdef _realtime_complette realtime
elif type complete &>/dev/null; then
  _realtime_complette() {
    COMPREPLY=( $(compgen -W '$(realtime --compbash --compgen "${COMP_CWORD}" "${COMP_WORDS[COMP_CWORD-1]}" "${COMP_LINE}")' -- "${COMP_WORDS[COMP_CWORD]}") )
  }
  complete -F _realtime_complette realtime
fi
### realtime completion - end ###
