ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

alias desk="~/Desktop"
alias db="~/Dropbox"
alias doit="git rev-parse --abbrev-ref HEAD | xargs git pull --rebase origin  && git rev-parse --abbrev-ref HEAD | xargs git push origin "
alias doitbig="git stash && git rev-parse --abbrev-ref HEAD | xargs git pull --rebase origin  && git rev-parse --abbrev-ref HEAD | xargs git push origin && git stash pop"

unsetopt correct
unsetopt correct_all

plugins=(git osx)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:/usr/local/sbin:$PATH::/Users/dseravalli/bin

### realtime completion - begin. generated by omelette ###
if type compdef &>/dev/null; then
  _realtime_complette() {
    compadd -- `realtime --compzsh --compgen "${CURRENT}" "${words[CURRENT-1]}" "${BUFFER}"`
  }
  compdef _realtime_complette realtime
elif type complete &>/dev/null; then
  _realtime_complette() {
    COMPREPLY=( $(compgen -W '$(realtime --compbash --compgen "${COMP_CWORD}" "${COMP_WORDS[COMP_CWORD-1]}" "${COMP_LINE}")' -- "${COMP_WORDS[COMP_CWORD]}") )
  }
  complete -F _realtime_complette realtime
fi
### realtime completion - end ###

export PATH="$HOME/.rbenv/bin:$PATH:/usr/local/opt/coreutils/libexec/gnubin:"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

eval "$(rbenv init -)"
. ~/.nvm/nvm.sh
